server:
  port: 8093
spring:
  application:
    name: nacos-consul-adapter
  cloud:
    nacos:
      discovery:
        server-addr: 147.128.16.106:8848
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}